// Writes abi/index.ts from the compiled artifacts. Run after `hardhat compile`; imported by web/.
import hre from 'hardhat';
import fs from 'node:fs';
import path from 'node:path';

const EXPORTS: [name: string, artifact: string][] = [
  ['tapebookClaimsAbi', 'TapebookClaims'],
  ['circuitFactoryAbi', 'CircuitFactory'],
  ['circuitsAbi', 'Circuits'],
  ['transistorsAbi', 'Transistors'],
  ['upgradeableBeaconAbi', 'UpgradeableBeacon'],
];

async function main() {
  let out = '// Generated by scripts/export-abi.ts from the compiled artifacts. Do not edit.\n';
  for (const [name, artifact] of EXPORTS) {
    const a = await hre.artifacts.readArtifact(artifact);
    out += `\nexport const ${name} = ${JSON.stringify(a.abi, null, 2)} as const;\n`;
  }
  const file = path.join(__dirname, '..', 'abi', 'index.ts');
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, out);
  console.log(`wrote ${path.relative(process.cwd(), file)}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
